workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "io.codemagic.sample.reactnative"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Update Expo and related packages
        script: |
          npm install expo@latest
          npm install --save-dev @expo/cli@latest
          npx expo install --check
      - name: Install required packages
        script: |
          npx expo install expo-system-ui
      - name: Check required asset files
        script: |
          for file in icon.png adaptive-icon.png splash.png favicon.png; do
            if [ ! -f "./assets/$file" ]; then
              echo "Error: $file is missing in the assets folder"
              exit 1
            fi
          done
      - name: Check assets folder
        script: |
          ls -R ./assets
      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild --clean
      - name: Build Android release
        script: | 
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - user_1@example.com
          - user_2@example.com
        notify:
          success: true
          failure: false